// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// Drug is the predicate function for drug builders.
type Drug func(*sql.Selector)

// Nurse is the predicate function for nurse builders.
type Nurse func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Prescription is the predicate function for prescription builders.
type Prescription func(*sql.Selector)
