// Code generated by entc, DO NOT EDIT.

package patient

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPatientName holds the string denoting the patient_name field in the database.
	FieldPatientName = "patient_name"

	// EdgePatientPrescription holds the string denoting the patient_prescription edge name in mutations.
	EdgePatientPrescription = "patient_prescription"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// PatientPrescriptionTable is the table the holds the patient_prescription relation/edge.
	PatientPrescriptionTable = "prescriptions"
	// PatientPrescriptionInverseTable is the table name for the Prescription entity.
	// It exists in this package in order to avoid circular dependency with the "prescription" package.
	PatientPrescriptionInverseTable = "prescriptions"
	// PatientPrescriptionColumn is the table column denoting the patient_prescription relation/edge.
	PatientPrescriptionColumn = "patient_id"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldPatientName,
}

var (
	// PatientNameValidator is a validator for the "Patient_Name" field. It is called by the builders before save.
	PatientNameValidator func(string) error
)
