// Code generated by entc, DO NOT EDIT.

package nurse

const (
	// Label holds the string label denoting the nurse type in the database.
	Label = "nurse"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNurseEmail holds the string denoting the nurse_email field in the database.
	FieldNurseEmail = "nurse_email"
	// FieldNurseName holds the string denoting the nurse_name field in the database.
	FieldNurseName = "nurse_name"
	// FieldNurseTel holds the string denoting the nurse_tel field in the database.
	FieldNurseTel = "nurse_tel"
	// FieldNursePassword holds the string denoting the nurse_password field in the database.
	FieldNursePassword = "nurse_password"

	// EdgeNursePrescription holds the string denoting the nurse_prescription edge name in mutations.
	EdgeNursePrescription = "nurse_prescription"

	// Table holds the table name of the nurse in the database.
	Table = "nurses"
	// NursePrescriptionTable is the table the holds the nurse_prescription relation/edge.
	NursePrescriptionTable = "prescriptions"
	// NursePrescriptionInverseTable is the table name for the Prescription entity.
	// It exists in this package in order to avoid circular dependency with the "prescription" package.
	NursePrescriptionInverseTable = "prescriptions"
	// NursePrescriptionColumn is the table column denoting the nurse_prescription relation/edge.
	NursePrescriptionColumn = "nurse_id"
)

// Columns holds all SQL columns for nurse fields.
var Columns = []string{
	FieldID,
	FieldNurseEmail,
	FieldNurseName,
	FieldNurseTel,
	FieldNursePassword,
}

var (
	// NurseEmailValidator is a validator for the "Nurse_Email" field. It is called by the builders before save.
	NurseEmailValidator func(string) error
	// NurseNameValidator is a validator for the "Nurse_Name" field. It is called by the builders before save.
	NurseNameValidator func(string) error
	// NurseTelValidator is a validator for the "Nurse_Tel" field. It is called by the builders before save.
	NurseTelValidator func(string) error
	// NursePasswordValidator is a validator for the "Nurse_Password" field. It is called by the builders before save.
	NursePasswordValidator func(string) error
)
