/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Prescription
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntNurseEdges,
    EntNurseEdgesFromJSON,
    EntNurseEdgesFromJSONTyped,
    EntNurseEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntNurse
 */
export interface EntNurse {
    /**
     * NurseEmail holds the value of the "Nurse_Email" field.
     * @type {string}
     * @memberof EntNurse
     */
    nurseEmail?: string;
    /**
     * NurseName holds the value of the "Nurse_Name" field.
     * @type {string}
     * @memberof EntNurse
     */
    nurseName?: string;
    /**
     * NursePassword holds the value of the "Nurse_Password" field.
     * @type {string}
     * @memberof EntNurse
     */
    nursePassword?: string;
    /**
     * NurseTel holds the value of the "Nurse_Tel" field.
     * @type {string}
     * @memberof EntNurse
     */
    nurseTel?: string;
    /**
     * 
     * @type {EntNurseEdges}
     * @memberof EntNurse
     */
    edges?: EntNurseEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntNurse
     */
    id?: number;
}

export function EntNurseFromJSON(json: any): EntNurse {
    return EntNurseFromJSONTyped(json, false);
}

export function EntNurseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntNurse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nurseEmail': !exists(json, 'Nurse_Email') ? undefined : json['Nurse_Email'],
        'nurseName': !exists(json, 'Nurse_Name') ? undefined : json['Nurse_Name'],
        'nursePassword': !exists(json, 'Nurse_Password') ? undefined : json['Nurse_Password'],
        'nurseTel': !exists(json, 'Nurse_Tel') ? undefined : json['Nurse_Tel'],
        'edges': !exists(json, 'edges') ? undefined : EntNurseEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntNurseToJSON(value?: EntNurse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Nurse_Email': value.nurseEmail,
        'Nurse_Name': value.nurseName,
        'Nurse_Password': value.nursePassword,
        'Nurse_Tel': value.nurseTel,
        'edges': EntNurseEdgesToJSON(value.edges),
        'id': value.id,
    };
}


