/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Prescription
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPrescription,
    EntPrescriptionFromJSON,
    EntPrescriptionFromJSONTyped,
    EntPrescriptionToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientEdges
 */
export interface EntPatientEdges {
    /**
     * PatientPrescription holds the value of the patient_prescription edge.
     * @type {Array<EntPrescription>}
     * @memberof EntPatientEdges
     */
    patientPrescription?: Array<EntPrescription>;
}

export function EntPatientEdgesFromJSON(json: any): EntPatientEdges {
    return EntPatientEdgesFromJSONTyped(json, false);
}

export function EntPatientEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientPrescription': !exists(json, 'patientPrescription') ? undefined : ((json['patientPrescription'] as Array<any>).map(EntPrescriptionFromJSON)),
    };
}

export function EntPatientEdgesToJSON(value?: EntPatientEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patientPrescription': value.patientPrescription === undefined ? undefined : ((value.patientPrescription as Array<any>).map(EntPrescriptionToJSON)),
    };
}


